# Generated by Django 2.2.16 on 2022-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220719_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MODERATOR', 'Модератор'), ('USER', 'Пользователь')], default='user', max_length=50),
        ),
    ]
